name:                cis194
version:             0.1.0.0
github:              "galenguyer/cis194"
license:             BSD3
author:              "Galen Guyer"
maintainer:          "galen@galenguyer.com"
copyright:           "2022 Galen Guyer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/galenguyer/cis194#readme>

dependencies:
- base >= 4.7 && < 5
- tasty >= 1.4 && < 1.5
- tasty-hunit > 0.10 && < 0.11
- tasty-quickcheck > 0.10 && < 0.11
- tasty-smallcheck > 0.8 && < 0.9

library:
  source-dirs: src

tests:
  cis194-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cis194
